name: sunny_fluro
version: 1.8.0-nullsafe.4
homepage: https://github.com/SunnyApp/fluro
description: Sunny Fluro is a fork of the popular fluro router for Flutter that adds the option for typed routes\n
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  logging: ^1.0.0
  pedantic: ^1.11.0
  dartxx: ^0.4.5-nullsafety.8
  uri: ^1.0.0
  sunny_dart: ^0.8.3+3
  flutter: 
    sdk: flutter
dev_dependencies: 
  test: any
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: false
