name: sunny_fluro
version: 1.7.0
homepage: https://github.com/SunnyApp/fluro
description: Sunny Fluro is a fork of the popular fluro router for Flutter that adds the option for typed routes\n
environment: 
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  logging: ^0.11.4
  pedantic: ^1.9.2
  uri: ^0.11.3+1
  sunny_dart: ^0.6.0+4
  flutter: 
    sdk: flutter
dev_dependencies: 
  test: ^1.15.7
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: false
