name: fluro
description: >
  Fluro is a Flutter routing library that adds flexible routing options like wildcards, named
  parameters and clear route definitions.
version: 1.6.1
homepage: https://github.com/theyakka/fluro

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  pedantic: ^1.9.2
  uri: ^0.11.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7

flutter:
  uses-material-design: false
