targets:
  $default:
    builders:
      fluro:
        enabled: true
      fluro_routes:
        enabled: true
      fluro_route:
        enabled: true

builders:
  fluro:
    import: "package:sunny_fluro_generator/build.dart"
    builder_factories: [ "fluroBuilder" ]
    build_extensions: { ".dart": [ ".fluro.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]

  fluro_routes:
    import: "package:sunny_fluro_generator/build.dart"
    builder_factories: [ "fluroRoutesBuilder" ]
    build_extensions: { ".dart": [ ".routes.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]

  fluro_route:
    import: "package:sunny_fluro_generator/build.dart"
    builder_factories: [ "fluroRouteBuilder" ]
    build_extensions: { ".dart": [ ".route.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]

