name: sunny_fluro_generator
description: >
  A generator that assists in creating typed routes and parameters
version: 1.8.0-nullsafe.2
homepage: https://github.com/SunnyApp/fluro/fluro_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  sunny_fluro: ^1.7.0+1
  flutter_degen: ^0.5.1-nullsafety.2
  build_runner: ^1.12.2
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^1.2.0

#  analyzer: ^0.41.1
#  build: ^1.5.2
#  args: ^1.6.0
#  path: ^1.7.0
#  dart_style: ^1.3.10
#  dartx: ^0.5.0
  pedantic: ^1.11.0
  uri: ^1.0.0
dev_dependencies:
  build_config: ^0.4.7
  test: ^1.16.8

flutter:
  uses-material-design: false
