name: sunny_fluro_generator
description: >
  A generator that assists in creating typed routes and parameters
version: 1.6.1
homepage: https://github.com/SunnyApp/fluro/fluro_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  sunny_fluro: any
  flutter_degen: ^0.4.5+5
  build_runner: ^1.10.13
  source_gen: ^0.9.10+1

#  analyzer: ^0.41.1
#  build: ^1.5.2
#  args: ^1.6.0
#  path: ^1.7.0
#  dart_style: ^1.3.10
#  dartx: ^0.5.0
  pedantic: ^1.9.2
  uri: ^0.11.3+1
dev_dependencies:
  build_config: ^0.4.5
  test: ^1.15.7

dependency_overrides:
  sunny_fluro:
    path: ../
  flutter_degen:
    path: ../../flutter_degen
flutter:
  uses-material-design: false
